### ISSUE TITLE
Events Proposal

### ISSUE THREAD

**Issue by patrickml** [timbrandin/meteor-react-sideburns#3]
So, it seems like react doesnt have the same kind of event listeners as meteor meaning there isnt a way to say if this component is click on this element then perform blah. Instead the event is tracked directly from the element using onClick, onScroll, ... onBlah. Well this means that the event listener should be directly tied to the element not its parents so it should react faster I would assume since it doesnt need to bubble down?

with this being said it kinda of make since and forces you to build your app into to components like so.

Here is a simple carousel component

~~~

<template name="Carousel">
  <ul class="carousel">
    {
      this.props.photos.map(function(val, index) {
        return <CarouselImage key={index} val={val} />
      })
    }
  </ul>
</template>

~~~

and here is the image component of the carousel

~~~

<template name="CarouselImage">
  <li onClick={Template.CarouselImage.events.click.bind(null, this.props)}><img src={this.props.val.photo} ref="image" /></li>
</template>

~~~

Be making each part of the carousel a component I am able to loop through the data binding `onClick={Template.CarouselImage.events.click.bind(null, this.props)}`

which looks like this

~~~

Template.CarouselImage.events = {
  'click' : function (props) {

}
}

~~~

In order to get this simple and logical approach working I only had to add one line to the compiler

~~~
jsx += "  events: function(o) {return this._events = o || (this._events || {})},\n";
~~~

What do you think?

**Comment by patrickml** [comment]
@timbrandin any thoughts?

**Comment by timbrandin** [comment]
Nice. yeah, I was trying a similar approach with less code, but we could support both ways actually if we store the events in _events.

In my approach I tried also parsing out the css-selector part just like blaze does.
You know this thing that we have ```"click li": function() {"```
> You can check it out here: https://github.com/timbrandin/meteor-react-jsx-templating/tree/feature-template-events

**Comment by timbrandin** [comment]
@patrickml I've updated the readme for a suggested better API, what's your thoughts?
https://github.com/timbrandin/meteor-react-jsx-templating/blob/feature-template-events/README.md

**Comment by timbrandin** [comment]
I've implemented a version of events now that fully supports meteor style event mapping. :)

**Comment by patrickml** [comment]
Sweeeet il check it out
